# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - doxygen
  jobs:
    pre_build:
      - mkdir docs/build
      - doxygen docs/doxy.cfg

